// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * chin_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * chinback_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Chintendo_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * gan_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * close_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * shin1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * cum_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_chintendo_png);    // assets/chintendo.png
LV_IMG_DECLARE(ui_img_chin1_png);    // assets/chin1.png
LV_IMG_DECLARE(ui_img_gan_png);    // assets/gan.png
LV_IMG_DECLARE(ui_img_close_png);    // assets/close.png
LV_IMG_DECLARE(ui_img_shin_png);    // assets/shin.png
LV_IMG_DECLARE(ui_img_cum1_png);    // assets/cum1.png
LV_IMG_DECLARE(ui_img_iku_png);    // assets/iku.png
LV_IMG_DECLARE(ui_img_chin2_png);    // assets/chin2.png
LV_IMG_DECLARE(ui_img_chinback1_png);    // assets/chinback1.png
LV_IMG_DECLARE(ui_img_chinback2_png);    // assets/chinback2.png
LV_IMG_DECLARE(ui_img_cum2_png);    // assets/cum2.png
LV_IMG_DECLARE(ui_img_cum3_png);    // assets/cum3.png
LV_IMG_DECLARE(ui_img_cum4_png);    // assets/cum4.png
LV_IMG_DECLARE(ui_img_cum5_png);    // assets/cum5.png
LV_IMG_DECLARE(ui_img_cum6_png);    // assets/cum6.png
LV_IMG_DECLARE(ui_img_cum7_png);    // assets/cum7.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
