// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cum_Animation(ui_Image8, 250);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xDFF8D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image8, &ui_img_cum1_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 148
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 155
    lv_obj_set_x(ui_Image8, 1);
    lv_obj_set_y(ui_Image8, -2);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 200);

    ui_Image1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image1, &ui_img_iku_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image1, -28);
    lv_obj_set_y(ui_Image1, -42);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 220);

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 30);
    lv_obj_set_y(ui_Label2, 37);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Strokes: 0");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 33);
    lv_obj_set_y(ui_Label1, 24);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Time: 0");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image8 = NULL;
    ui_Image1 = NULL;
    ui_Label2 = NULL;
    ui_Label1 = NULL;

}
